#! perl

# $Id$

# pragmata
use strict;
use warnings;
use Getopt::Long;
use 5.008;

my $pbc = 'perl5.pbc';

my @tests = (<t/*.t>,<t/*/*.t>, <t/spec/*/*.t>);

# Determine if perl6 is in our $PATH
system("perl6 -e42");
if ($? == -1 or ($? & 127)) {
    @tests = grep { $_ !~ /perl6/ } @tests;
    print "No working perl6 binary found in your path. Perl 6 tests disabled. :(\n";
} else {
    print "Found a working perl6 binary in your path. Perl 6 tests enabled. :)\n";
}

our %harness_args = (
    language  => 'blizkost',
    verbosity => 0,
    jobs      => $ENV{TEST_JOBS} || 1,
    files     => \@tests,
    merge     => 0,
);

GetOptions(
        'verbosity=i'       => \$harness_args{verbosity},
        'bindir=s'          => \my $bindir,
        # A sensible default is num_cores + 1.
        # Many people have two cores these days.
        'jobs:3'            => \$harness_args{jobs},
);

if ($bindir) {
    $harness_args{exec} = [$bindir.'/parrot', $pbc ];
}
else {
    $harness_args{compiler} = $pbc;
}

eval 'use Parrot::Test::Harness %harness_args';

